function tests = get_element_children_test
tests = functiontests(localfunctions);
end

function two_dimensional_test(testCase)

[lev,pos,cnt] = get_element_children ([3,2], [1,0], 6);

gold_lev = [    [4,2]' ...
                [4,2]' ...
                [3,3]' ...
                [3,3]' ...
                [4,3]' ...
                [4,3]' ...
                [4,3]' ...
                [4,3]' ];
            
gold_pos = [    [2,0]' ...
                [3,0]' ...
                [1,0]' ...
                [1,1]' ...
                [2,0]' ...
                [2,1]' ...
                [3,0]' ...
                [3,1]' ];

assert( norm(gold_lev'-lev) == 0);

end