% Plotting Grid
close all
clc

% Setting Lev

Lev=6;

% Uniform grid for 2D and ignoring Deg
xx=zeros(2^Lev,1);
count=1;
for l=0:Lev
    for c=0:2^max(l-1,0)-1
        if l==0
            h=1/2;
            xx(count)=0.5;
        else
            h=1/2^(l-1);
            xx(count)=(h*c+h*c+h)/2;
        end
        
        
        count=count+1;
    end
end

% Full Grid is generated by 1D xx
[FullGridX,FullGridY]=meshgrid(xx);


count=1;
% Sparse Grid is generated by combination of xx and yy
for lx=0:Lev
    for ly=0:Lev-lx
        for cx=0:2^max(lx-1,0)-1
            for cy=0:2^max(ly-1,0)-1
                if lx==0
                    h=1/2;
                    xx(count)=0.5;
                else
                    h=1/2^(lx-1);
                    xx(count)=(h*cx+h*cx+h)/2;
                end
                
                if ly==0
                    h=1/2;
                    yy(count)=0.5;
                else
                    h=1/2^(ly-1);
                    yy(count)=(h*cy+h*cy+h)/2;
                end
                
                
                
                count=count+1;
            end
        end
    end
end

figure;
subplot(1,2,1)
plot(FullGridX(:),FullGridY(:),'r.')
subplot(1,2,2)
plot(xx,yy,'r.')

DOF_FG=size(FullGridX(:),1);
DOF_SG=size(xx,1);
'DOF comparison is as follows'

[DOF_FG DOF_SG]
