function [b_s,E_s,B_s]=GlobalRHS(Deg,F_1D,E_1D,B_1D,InvHash)
%=====================================================
% Generate RHS for Maxwell's equations on [0,Lmax]^3
% Output: 
%   b_s Right Hand Side Vector
%   E_s Initial Condition for E
%   B_s Initial Condition for B
%=====================================================
HashDof=size(InvHash,2);
dof_sparse1=double(HashDof)*Deg^3;
dof_sparse = 3*dof_sparse1;

b_s=sparse(dof_sparse,1);

% interpolation of exact solution
B_s=sparse(dof_sparse,1);
E_s=sparse(dof_sparse,1);


for i=1:HashDof
    ll=InvHash{i};
    % Index from Hash
    iInd1=ll(7);iInd2=ll(8);iInd3=ll(9);
    
    tmp1=Deg*(iInd1-1)+1:Deg*iInd1;
    tmp2=Deg*(iInd2-1)+1:Deg*iInd2;
    tmp3=Deg*(iInd3-1)+1:Deg*iInd3;
    
    val1=kron(F_1D.b3x1(tmp1), ...
         kron( F_1D.b3y1(tmp2),F_1D.b3z1(tmp3) )...
        )...
        +kron(F_1D.b4x1(tmp1),...
        kron(F_1D.b4y1(tmp2),F_1D.b4z1(tmp3) )...
        );
    val2=kron(F_1D.b3x2(tmp1),...
        kron(F_1D.b3y2(tmp2),F_1D.b3z2(tmp3))...
        )...
        +kron(F_1D.b4x2(tmp1),...
        kron(F_1D.b4y2(tmp2),F_1D.b4z2(tmp3))...
        );
    val3=kron(F_1D.b3x3(tmp1),...
        kron(F_1D.b3y3(tmp2),F_1D.b3z3(tmp3))...
        )...
        +kron(F_1D.b4x3(tmp1),...
        kron(F_1D.b4y3(tmp2),F_1D.b4z3(tmp3))...
        );
    
    index=Deg^3*(i-1)+1:Deg^3*i;

    b_s(  index)=b_s(index)+val1;
    b_s(  dof_sparse1+index)=b_s(  dof_sparse1+index)+val2;
    b_s(2*dof_sparse1+index)=b_s(2*dof_sparse1+index)+val3;
    
    val1=kron(E_1D.Ex1(tmp1),...
        kron(E_1D.Ey1(tmp2),E_1D.Ez1(tmp3))...
        );
    val2=kron(E_1D.Ex2(tmp1),...
        kron(E_1D.Ey2(tmp2),E_1D.Ez2(tmp3))...
        );
    val3=kron(E_1D.Ex3(tmp1),...
        kron(E_1D.Ey3(tmp2),E_1D.Ez3(tmp3))...
        );
    
    E_s(  index)=E_s(index)+val1;
    E_s(  dof_sparse1+index)=E_s(dof_sparse1+index)+val2;
    E_s(2*dof_sparse1+index)=E_s(2*dof_sparse1+index)+val3;
    
    val1=kron(B_1D.Bx1(tmp1),...
        kron(B_1D.By1(tmp2),B_1D.Bz1(tmp3))...
        );
    val2=kron(B_1D.Bx2(tmp1),...
        kron(B_1D.By2(tmp2),B_1D.Bz2(tmp3))...
        );
    val3=kron(B_1D.Bx3(tmp1),...
        kron(B_1D.By3(tmp2),B_1D.Bz3(tmp3))...
        );
    
    B_s(  index)=B_s(index)+val1;
    B_s(  dof_sparse1+index)=B_s(dof_sparse1+index)+val2;
    B_s(2*dof_sparse1+index)=B_s(2*dof_sparse1+index)+val3;

end



